add some preliminary logic

diff --git a/bin/btfc b/bin/btfc
--- a/bin/btfc
+++ b/bin/btfc
@@ -31,6 +31,190 @@
 ######################################################################
 SCRIPTVERSION=150121-075208
 
+
+########## Variables
+
+
+BTFCMETA="~/.btfcmeta"
+BTFCCACHE="~/.btfccache"
+BTFCTMP="~/.btfctmp"
+
+
+########## Functions
+
+
+exiterror() {
+  if [ "$1" != "0" ]; then
+    echo "ERROR: $1 $2" >&2
+  fi
+  exit $1
+}
+
+
+hashpath() {
+  if [ -d "${PATH}" ]; then
+    cd "${PATH}"
+    FULLPATH=`pwd`
+    cd -
+    echo "${FULLPATH}" | shasum -a 1 | grep -o '[a-zA-Z0-9]*'
+  else
+    exiterror 1 "${PATH} is not a directory."
+  fi
+}
+
+
+########## modified from \
+# http://edwardslab.bmcb.georgetown.edu/software/bittorrent_for_clusters.html
+validpid() {
+  if [ -f "$1" ]; then
+    ps `cat $1` >/dev/null 2>&1
+    return $?
+  else
+    return 1
+  fi
+}
+
+
+copy_path_to_cache() {
+  if [ "$HARDLINK" = "-l" ]; then
+    if [ "x" != "x${HASHOFPATH}" ]; then
+      #hardcoded so we don't delete /
+      if [ -d "~/.btfccache/${HASHOFPATH}" ]; then
+        rm -r "~/.btfccache/${HASHOFPATH}" || exiterror 1 "Can't rm -r ~/.btfccache/${HASHOFPATH}"
+      fi
+      install -d -m 700 "${BTFCCACHE}/${HASHOFPATH}"
+      cp -rl "${FULLPATH}" "${BTFCCACHE}/${HASHOFPATH}/" || exiterror 1 "Can't cp -rl ${FULLPATH} ${BTFCCACHE}/${HASHOFPATH}/"
+    else
+      exiterror 1 "Can't sha1 the path."
+    fi
+  else
+    rsync -rq $RSYNCCHECK $1 "${FULLPATH}/" "${BTFCCACHE}/${HASHOFPATH}/${FULLPATH##*/}/"
+  fi
+}
+
+copy_to_fullpath() {
+  # ...... if -p prune: try rsync --delete
+  rsync -rq $RSYNCCHECK $RSYNCDELETE "${BTFCCACHE}/${HASHOFPATH}/${FULLPATH##*/}/" "${FULLPATH}/"
+}
+
+
+make_torrent() { #TODO XXXXX
+
+}
+
+
+start_transmissioncli() { #TODO XXXXX
+  # ...... run torrent client with metadata from ~/.btfcmeta/folder.torrent and saving data to ~/.btfccache/folder
+  # ...... on complete: rsync with (-c default, -t speed) and with backup or save conflict copy to ~/btfc/folder
+  copy_to_fullpath
+}
+
+
+kill_transmissioncli() { #TODO XXXXX
+
+}
+
+
+prune_by_grep() { #TODO XXXXX
+  if [ "$PRUNE" = "-p" ]; then
+    # if grep file name not in .torrent, unlink the .btfccache/hash_of_pathname/folder/path/file
+  fi
+}
+
+
+subscribe_using() {
+  if [ "$1" = "copy" ]; then
+    if [ "x" != "x${WATCH}" ]; then
+      if [ -e "${WATCH}/${HASHOFPATH}.torrent" ]; then
+        cp "${WATCH}/${HASHOFPATH}.torrent" "${BTFCTMP}/${HASHOFPATH}.torrent"
+      fi
+    else
+      exiterror 1 "-w is not specified."
+    fi
+  fi
+}
+
+
+publish_using() {
+  if [ "$1" = "copy-git-add-commit" ]; then
+    cp "${BTFCMETA}/${HASHOFPATH}.torrent" "${WATCH}/${HASHOFPATH}.torrent"
+    cd "${WATCH}"
+    git add "${HASHOFPATH}.torrent"
+    git commit -m "updated ${HASHOFPATH}.torrent"
+    cd -
+  fi
+}
+
+
+leech() {
+  # ...... stop client
+  kill_transmissioncli
+  # ...... if seeding but .torrent different then
+  if [ "$STATUS" = "-S" ]; then
+    # ........ rsync ~/folder/ ~/.btfccache/hash_of_pathname/folder/ (or if -l, rm -rf ~/.btfccache/hash_of_pathname/folder + cp -rl for speed)
+    copy_path_to_cache
+    # ...... fi
+  fi
+  mv "${BTFCTMP}/${HASHOFPATH}.torrent" "${BTFCMETA}/${HASHOFPATH}.torrent"
+  # ...... if -p prune: try if grep file name not in .torrent, unlink the .btfccache/hash_of_pathname/folder/path/file
+  [ "$PRUNE" = "-p" ] && prune_by_grep
+  start_transmissioncli
+}
+
+while getopts w:d:P:s:iclpSLvh o; do
+  case "$o" in
+    w) WATCH="${OPTARG}" ;;
+    d) PATH="${OPTARG}" ;;
+    P) PORT="${OPTARG}" ;;
+    s) WAITSECONDS="${OPTARG}" ;;
+    i) ACTION="init" ;;
+    c) ACTION="clone" ;;
+    l) HARDLINK="-l" ;;
+    p) PRUNE="-p" ;;
+    S) STATUS="-S" ;; #seeding
+    L) STATUS="-L" ;; #leeching
+    v) echo "$SCRIPTVERSION" ; exit 1 ;;
+    h) usage ; exit 1 ;;
+    [?]) usage ; exit 1 ;;
+  esac
+done
+
+
+########## default variable settings if not found
+if [ "x" = "x${WATCH}" ]; then
+  WATCH="~/gitsync"
+fi
+if [ "x" = "x${PATH}" ]; then
+  PATH="~/btfc"
+fi
+PORT=`echo $PORT | grep -o '[0-9]*'`
+if [ "x" = "x${PORT}" ]; then
+  PORT="51413"
+fi
+WAITSECONDS=`echo $WAITSECONDS | grep -o '[0-9]*'`
+if [ "x" = "x${WAITSECONDS}" ]; then
+  WAITSECONDS="60"
+fi
+if [ "x" = "x${ACTION}" ]; then
+  exiterror 1 "Required -i or -c."
+fi
+if [ "x" = "x${STATUS}" ]; then
+  STATUS="-L"
+fi
+[ "$PRUNE" = "-p" ] && RSYNCDELETE="--delete"
+RSYNCCHECK="-c"
+[ "$HARDLINK" = "-l" ] && RSYNCCHECK="-t"
+
+HASHOFPATH=`hashpath`
+if [ "x" = "x${HASHOFPATH}" ]; then
+  exiterror 1 "Can't sha1 the path."
+fi
+if [ "x" = "x${FULLPATH}" ]; then
+  exiterror 1 "Can't pwd in the path."
+fi
+
+
+if [ "$ACTION" = "init" ]; then
 # PSEUDO CODE
 #
 # btfc -i [-l] [-p] [-d directory] [-P PORT] [-s seconds]
@@ -41,36 +225,59 @@ SCRIPTVERSION=150121-075208
 # .. -P for TCP/IP port
 # .. -s for INTERVAL in seconds
 # .. if client not running
+     if ! validpid ${HASHOFPATH} ; then
 # .... if ! diff -r ~/.btfccache/hash_of_pathname/folder ~/folder (different)
+       install -d -m 700 "${BTFCCACHE}/${HASHOFPATH}/${FULLPATH##*/}"
+       if ! diff -r -q "${FULLPATH}/" "${BTFCCACHE}/${HASHOFPATH}/${FULLPATH##*/}/" ; then
 # ...... rsync ~/folder/ ~/.btfccache/hash_of_pathname/folder/ (or if -l, rm -rf ~/.btfccache/hash_of_pathname/folder + cp -rl for speed)
+         copy_path_to_cache --delete
 # ...... create ~/.btfctmp/folder.torrent file from ~/.btfccache/hash_of_pathname/folder
+         make_torrent
 # .... fi
+       fi
 # .... if ~/.btfcmeta/folder.torrent not exist
+       if [ ! -e "${BTFCMETA}/${HASHOFPATH}.torrent" ]; then
 # ...... rsync ~/folder/ ~/.btfccache/hash_of_pathname/folder/ (or if -l, rm -rf ~/.btfccache/hash_of_pathname/folder + cp -rl for speed)
+         copy_path_to_cache --delete
 # ...... create ~/.btfctmp/folder.torrent file from ~/.btfccache/hash_of_pathname/folder
+         make_torrent
 # .... fi
+       fi
 # .... PUBLISH (using the copy+git commit strategy) from ~/.btfctmp/folder.torrent to ~/gitsync (in gtfc if gitsync exists)
+       publish_using copy-git-add-commit
+       STATUS="-S"
 # .. fi
+     fi
 # .. run btfc -c [-l] [-p] [-d directory] [-P PORT] [-s seconds]
+     ${0} -c $HARDLINK $PRUNE -d $FULLPATH -P $PORT -s $WAITSECONDS -w $WATCH $STATUS &
 #
+elif [ "$ACTION" = "clone" ]; then
 # btfc -c [-l] [-p] [-d directory] [-P PORT] [-s seconds]
 # .. -c means clone
 # .. SUBSCRIBE (using copy strategy) from ~/gitsync to ~/.btfctmp/folder.torrent
+     subscribe_using copy
 # .. if ! diff ~/.btfctmp/folder.torrent ~/.btfcmeta/folder.torrent (different)
-# .... if seeding(100%), leeching(not100%) or nostate(?) but .torrent different then
-# ...... stop client
+     if   [ -e "${BTFCTMP}/${HASHOFPATH}.torrent" ] && [ ! -e "${BTFCMETA}/${HASHOFPATH}.torrent" ]; then
+       leech
+     elif [ -e "${BTFCTMP}/${HASHOFPATH}.torrent" ] && [   -e "${BTFCMETA}/${HASHOFPATH}.torrent" ]; then
+       if ! diff -q "${BTFCTMP}/${HASHOFPATH}.torrent" "${BTFCMETA}/${HASHOFPATH}.torrent" ; then
+         leech
 # .... fi
-# .... if seeding or nostate but .torrent different then
-# ...... rsync ~/folder/ ~/.btfccache/hash_of_pathname/folder/ (or if -l, rm -rf ~/.btfccache/hash_of_pathname/folder + cp -rl for speed)
-# .... fi
-# .... if -p prune: try if grep file name not in .torrent, unlink the .btfccache/hash_of_pathname/folder/path/file
-# .... run torrent client with metadata from ~/.btfcmeta/folder.torrent and saving data to ~/.btfccache/folder
-# .... on complete: rsync with (-c default, -t speed) and with backup or save conflict copy to ~/btfc/folder
-# .... if -p prune: try rsync --delete in above
-# .. fi
+       fi
+     fi
 # .. if ! diff -r ~/.btfccache/hash_of_pathname/folder ~/folder (different)
+     install -d -m 700 "${BTFCCACHE}/${HASHOFPATH}/${FULLPATH##*/}"
+     if ! diff -r -q "${FULLPATH}/" "${BTFCCACHE}/${HASHOFPATH}/${FULLPATH##*/}/" ; then
 # .... stop client
+       kill_transmissioncli
 # .. else
+     else
 # .... sleep for INTERVAL seconds
+       sleep $WAITSECONDS
 # .. fi
+     fi
 # .. run btfc -i [-l] [-p] [-d directory] [-P PORT] [-s seconds]
+     ${0} -i $HARDLINK $PRUNE -d $FULLPATH -P $PORT -s $WAITSECONDS -w $WATCH $STATUS &
+else
+  exit 1
+fi
